import Product from "@/components/screens/Product/Product";
import { IItem } from "@/types/IItem";
import { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { fetchItemById } from "../lib/fetchItemById";

const ProductPage: NextPage<{ item: IItem }> = ({ item }) => {
  return (
    <>
      <Head>
        <title>YORCOM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Product item={item} />
      </main>
    </>
  );
};

export default ProductPage;

export async function getStaticPaths() {
  return {
    paths: [
      {
        params: { id: "1" },
      },
      {
        params: { id: "2" },
      },
      {
        params: { id: "3" },
      },
    ],
    fallback: false,
  };
}

export const getStaticProps: GetStaticProps<{
  item: IItem;
}> = async (context) => {
  const { params } = context;
  const item = await fetchItemById(String(params?.id));
  return {
    props: {
      item,
    },
  };
};
