import Home from "@/components/screens/Home/Home";
import Head from "next/head";
import type { GetStaticProps, NextPage } from "next";
import { fetchItems } from "./lib/fetchItems";
import { IItem } from "@/types/IItem";

export interface IDataItems {
  items: IItem[];
}

export default function HomePage({ items }: IDataItems) {
  return (
    <>
      <Head>
        <title>YORCOM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Home items={items} />
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps<{
  items: IDataItems;
}> = async () => {
  const items = await fetchItems();
  return {
    props: {
      items,
    },
  };
};
